In [1]:
import gym 
import numpy as np
import math

In [2]:
env= gym.make('FrozenLake-v1')
env.reset()

0

In [3]:
print(env.observation_space)
print(env.action_space)

Discrete(16)
Discrete(4)


In [4]:
Q= np.zeros((16,4))
EP=100000
e=0.25
alpha=0.1
gamma=0.99
for ep in range(EP):
    state= env.reset()
        
    action= np.random.randint(4)
    done= False
    TR=0
    
    while not done:
        next_state, reward, done, info= env.step(action)

        
        P=[e/4]*4
        greedy_action= np.argmax(Q[next_state])
        P[greedy_action]+= (1-e)
        
        next_action= np.random.choice([0,1,2,3],p=P)
        

        
        Q[state][action]= Q[state][action]+ (alpha*(reward + (0.99*Q[next_state][next_action])- Q[state][action] ))
        
        state= next_state
        action= next_action
        
        TR+=reward
    
    print(ep, end='\r')
      

## Now we use these Q Values to reach the goal. let's see our success rate.

In [5]:
success=[]
total_run=10000
for episodes in range(total_run):
    
    state= env.reset()
    action= np.argmax(Q[state])
    done= False
    Tr=0
    while not done:
        
        next_state, reward, done, info= env.step(action)
        
        action= np.argmax(Q[next_state])
        
        state= next_state
        
        Tr+=reward

    success.append(Tr)
    

In [6]:
success_rate=100*success.count(1)/total_run
print(success_rate,"%")

64.0 %


In [7]:
temp=np.zeros(16)
for i in range(16):
    temp[i]= np.argmax(Q[i])

In [8]:
print(temp[0:4])
print(temp[4:8])
print(temp[8:12])
print(temp[12:16])

[0. 3. 1. 3.]
[0. 0. 2. 0.]
[3. 1. 0. 0.]
[0. 2. 2. 0.]
